import StyledWrapper from "./styled-wrapper";
import CustomI18nextProvider from "./providers/I18nextProvider";
import "./globals.css";
import "antd/dist/reset.css";
import ReduxProvider from "./redux-provider";

export const metadata = {
  title: "AriMayi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="w-screen h-screen flex">
        <ReduxProvider>
          <CustomI18nextProvider>
            <StyledWrapper>{children}</StyledWrapper>
          </CustomI18nextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
